### ISSUE TITLE
Direct Using Caps

### ISSUE THREAD

**Issue by lazyremixmanordummyplayinggmod** [Itz-Miles/parallaxLT#3]
**instead of vertical it could also be**

##  Vertical, VERTICAL
 
 Because the first time i was using fixate i got confused because it would not work at first

**Comment by Itz-Miles** [comment]
Sounds like a feature if you ask me! I'll implement that and release parallaxLT 0.0.2

**Comment by lazyremixmanordummyplayinggmod** [comment]
Thanks Will you add it will be Great
