### ISSUE TITLE
Scaling makes a Parallax Sprite disappear

### ISSUE THREAD

**Issue by lazyremixmanordummyplayinggmod** [Itz-Miles/parallaxLT#5]
I tried scaling a PS but it just disappears when the zoom is larger?
[Footage](https://streamable.com/d1yypr) has no sound

**Comment by Itz-Miles** [comment]
I'm currently implementing an optimized isOnScreen function. Wanted to get it out sooner, but life got in the way! I suggest you use 0.0.0 for a short time while I push changes.

**Comment by lazyremixmanordummyplayinggmod** [comment]
Ok thanks Though
